-- MySQL Script generated by MySQL Workbench
-- Wed Sep  7 18:21:31 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `baseDatosTinderPerros` ;

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `baseDatosTinderPerros` DEFAULT CHARACTER SET utf8 ;
USE `baseDatosTinderPerros` ;

-- -----------------------------------------------------
-- Table `baseDatosTinderPerros`.`Login`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `baseDatosTinderPerros`.`Login` ;

CREATE TABLE IF NOT EXISTS `baseDatosTinderPerros`.`Login` (
  `idLogin` INT NOT NULL AUTO_INCREMENT,
  `nombreUsuario` VARCHAR(15) NOT NULL,
  `contraseña` VARCHAR(12) NOT NULL,
  PRIMARY KEY (`idLogin`),
  UNIQUE INDEX `nombreUsuario_UNIQUE` (`nombreUsuario` ASC) VISIBLE,
  UNIQUE INDEX `idLogin_UNIQUE` (`idLogin` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `baseDatosTinderPerros`.`Persona`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `baseDatosTinderPerros`.`Persona` ;

CREATE TABLE IF NOT EXISTS `baseDatosTinderPerros`.`Persona` (
  `idPersona` INT NOT NULL AUTO_INCREMENT,
  `nombrePersona` VARCHAR(15) NULL,
  `apellidoPersona` VARCHAR(25) NULL,
  `descripcionPersona` VARCHAR(140) NULL,
  `etiquetasPersona` VARCHAR(45) NULL,
  `etiquetasMascotaes` VARCHAR(45) NULL,
  `numTelefono` INT(9) NULL,
  `Login_idLogin` INT NOT NULL,
  `fotoPerfilPersona` VARCHAR(45) NULL,
  `fechaNacimientoPersona` DATE NULL,
  `ciudadPuebloPersona` VARCHAR(45) NULL,
  PRIMARY KEY (`idPersona`),
  INDEX `fk_Personas_Login_idx` (`Login_idLogin` ASC) VISIBLE,
  CONSTRAINT `fk_Personas_Login`
    FOREIGN KEY (`Login_idLogin`)
    REFERENCES `baseDatosTinderPerros`.`Login` (`idLogin`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `baseDatosTinderPerros`.`RazasMascota`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `baseDatosTinderPerros`.`RazasMascota` ;

CREATE TABLE IF NOT EXISTS `baseDatosTinderPerros`.`RazasMascota` (
  `idRazasMascota` INT NOT NULL AUTO_INCREMENT,
  `nombreRaza` VARCHAR(45) NULL,
  UNIQUE INDEX `nombreRaza_UNIQUE` (`nombreRaza` ASC) VISIBLE,
  PRIMARY KEY (`idRazasMascota`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `baseDatosTinderPerros`.`Mascota`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `baseDatosTinderPerros`.`Mascota` ;

CREATE TABLE IF NOT EXISTS `baseDatosTinderPerros`.`Mascota` (
  `idMascota` INT NOT NULL AUTO_INCREMENT,
  `nombreMascota` VARCHAR(15) NULL,
  `descripcionMascota` VARCHAR(140) NULL,
  `etiquetasPersona` VARCHAR(45) NULL,
  `etiquetasMascota` VARCHAR(45) NULL,
  `numTelefono` INT(9) NULL,
  `Login_idLogin` INT NOT NULL,
  `fotoPerfilMascota` VARCHAR(45) NULL,
  `fotosMascota` VARCHAR(45) NULL,
  `fechaNacimientoMascota` DATE NULL,
  `RazasMascota_idRazasMascota` INT NOT NULL,
  `ciudadPuebloMascota` VARCHAR(45) NULL,
  PRIMARY KEY (`idMascota`, `RazasMascota_idRazasMascota`),
  INDEX `fk_Mascota_Login1_idx` (`Login_idLogin` ASC) VISIBLE,
  INDEX `fk_Mascota_RazasMascota1_idx` (`RazasMascota_idRazasMascota` ASC) VISIBLE,
  CONSTRAINT `fk_Mascota_Login1`
    FOREIGN KEY (`Login_idLogin`)
    REFERENCES `baseDatosTinderPerros`.`Login` (`idLogin`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Mascota_RazasMascota1`
    FOREIGN KEY (`RazasMascota_idRazasMascota`)
    REFERENCES `baseDatosTinderPerros`.`RazasMascota` (`idRazasMascota`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `baseDatosTinderPerros`.`Match`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `baseDatosTinderPerros`.`Match` ;

CREATE TABLE IF NOT EXISTS `baseDatosTinderPerros`.`Match` (
  `Mascota_idMascota` INT NOT NULL,
  `Persona_idPersona` INT NOT NULL,
  `estadoMatch` VARCHAR(45) NULL DEFAULT 'pendiente',
  PRIMARY KEY (`Mascota_idMascota`, `Persona_idPersona`),
  INDEX `fk_Mascota_has_Persona_Persona1_idx` (`Persona_idPersona` ASC) VISIBLE,
  INDEX `fk_Mascota_has_Persona_Mascota1_idx` (`Mascota_idMascota` ASC) VISIBLE,
  CONSTRAINT `fk_Mascota_has_Persona_Mascota1`
    FOREIGN KEY (`Mascota_idMascota`)
    REFERENCES `baseDatosTinderPerros`.`Mascota` (`idMascota`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Mascota_has_Persona_Persona1`
    FOREIGN KEY (`Persona_idPersona`)
    REFERENCES `baseDatosTinderPerros`.`Persona` (`idPersona`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

INSERT INTO basedatostinderperros.razasmascota(nombreRaza)VALUES
("Labrador retriever"),
("Bulldog francés"),
("Golden retriever"),
("Pastor alemán"),
("Caniche"),
("Bulldog"),
("Beagle"),
("Rottweiler"),
("Labrador"),
("Chihuahua");

SELECT * FROM razasmascota;